[theme]
base="light"
primaryColor="#1E90FF"  # Bleu clair pour les boutons et éléments interactifs
backgroundColor="#FFFFFF"  # Fond blanc
secondaryBackgroundColor="#F5F5F5"  # Fond des éléments secondaires (sidebar, boîtes)
textColor="#000000"  # Texte noir
font="sans serif"
